new config

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -1,15 +1,15 @@
 name: CD
 
 on:
-  push:
-    tags:
-      - 'v[0-9]+.[0-9]+.[0-9]+'
-      - 'v[0-9]+.[0-9]+.[0-9]+-*'
+  release:
+    types: [published]
 
 jobs:
   deploy:
+    if: startsWith(github.ref, "refs/tags/v")
     name: Deploy docker image
     runs-on: ubuntu-latest
+    environment: production
     permissions:
       contents: read
       packages: write
@@ -17,12 +17,36 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v5
+        with:
+          fetch-depth: 0
+
+      - name: Check tag's commit is in main
+        run: |
+          TAG_REF=${GITHUB_REF#refs/tags/}
+          COMMIT_SHA=$(git rev-list -n 1 ${TAG_REF})
+          git merge-base --is-ancestor ${COMMIT_SHA} origin/main || exit 1
+
+      - name: Check required vars
+        run: |
+          if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
+            echo "❌ DOCKERHUB_TOKEN is not defined in repo/environment secrets."
+            exit 1
+          fi
+          if [ -z "${{ vars.DOCKERHUB_USERNAME }}" ]; then
+            echo "❌ DOCKERHUB_USERNAME is not defined in repo/environment variables."
+            exit 1
+          fi
+          if [ -z "${{ vars.DOCKERHUB_IMAGE }}" ]; then
+            echo "❌ DOCKERHUB_IMAGE is not defined in repo/environment variables."
+            exit 1
+          fi
+          echo "✅ Required vars/secrets are set."
 
       - name: Docker meta
         id: meta
         uses: docker/metadata-action@v5
         with:
-          images: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPOSITORY }}
+          images: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_IMAGE }}
           tags: |
             type=semver,pattern={{version}},match=v(\d+.\d+.\d+)$
             type=semver,pattern={{major}}.{{minor}},match=v(\d+.\d+.\d+)$
@@ -43,10 +67,10 @@ jobs:
       - name: Build and push Docker image
         uses: docker/build-push-action@v6
         with:
-          context: ${{ vars.DOCKER_BUILD_CONTEXT }}
-          file: ${{ vars.DOCKER_CONFIG_FOLDER }}/Dockerfile
+          context: ${{ vars.DOCKER_BUILD_CONTEXT || '.' }}
+          file: ${{ vars.DOCKER_CONFIG_FOLDER || './.docker' }}/Dockerfile
           push: true
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}
           build-contexts: |
-            docker_config_folder=${{ vars.DOCKER_CONFIG_FOLDER }}
+            docker_config_folder=${{ vars.DOCKER_CONFIG_FOLDER || './.docker' }}
